[project]
name = "AttachmentsDownloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "prompt>=0.4.1",
]
[dependency-groups]
dev = [
    "ruff>=0.9.7",
]
